const assert = require('node:assert/strict');
const fs = require('node:fs');

const indexSource = fs.readFileSync('index.html', 'utf8');
const styleSource = fs.readFileSync('css/style.css', 'utf8');

assert.match(indexSource, /id="mobile-search-panel"/);
assert.match(indexSource, /id="mobile-maps-sheet"/);
assert.match(indexSource, /id="mobile-dock"/);
assert.match(indexSource, /id="mobile-explore-launcher-btn"/);
assert.match(indexSource, /id="mobile-maps-launcher-btn"/);
assert.match(indexSource, /id="mobile-search-panel-close-btn"/);
assert.match(indexSource, /id="mobile-maps-sheet-close-btn"/);
assert.match(indexSource, /id="mobile-current-map-summary-card"/);
assert.match(indexSource, /id="mobile-current-map-summary-name"/);
assert.match(indexSource, /id="mobile-current-map-summary-blurb"/);
assert.match(indexSource, /id="mobile-search-actions-card"/);
assert.match(indexSource, /id="mobile-utility-actions"/);
assert.match(indexSource, /id="mobile-markers-btn"/);
assert.match(indexSource, /id="mobile-measure-btn"/);
assert.match(indexSource, /id="mobile-share-view-btn"/);
assert.match(indexSource, /id="mobile-coords-btn"/);
assert.match(indexSource, /id="mobile-help-btn"/);
assert.match(indexSource, /id="mobile-maps-current-map-card"/);
assert.match(indexSource, /id="mobile-current-map-name"/);
assert.match(indexSource, /id="mobile-current-map-blurb"/);
assert.match(indexSource, /id="mobile-search-card"/);
assert.match(indexSource, /id="mobile-search-panel-search-slot"/);
assert.match(indexSource, /id="mobile-search-results-card"/);
assert.match(indexSource, /id="mobile-search-panel-results-slot"/);
assert.match(indexSource, /id="mobile-maps-sheet-map-list-slot"/);
assert.match(indexSource, /class="mobile-sheet-card"/);
assert.match(indexSource, /class="mobile-sheet-card-title-row"/);
assert.ok(indexSource.indexOf('id="mobile-search-panel"') < indexSource.indexOf('id="search-control-container"'));
assert.ok(indexSource.indexOf('id="mobile-dock"') < indexSource.indexOf('id="mobile-search-panel"'));
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout #mobile-search-panel,/);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout #mobile-maps-sheet \{/);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout #mobile-dock \{/);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout #mobile-explore-launcher-btn,/);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout \.mobile-sheet-card \{/);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout #mobile-search-results-card \{/);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout #mobile-search-panel #search-control-container \{/);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout #mobile-utility-actions \{/);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout #mobile-search-panel #search-refine-filters-btn,/);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout #mobile-search-panel #poi-filter-container\.visible \{/);
assert.doesNotMatch(indexSource, /id="mobile-search-trigger"/);
assert.doesNotMatch(indexSource, /id="mobile-search-shell"/);
assert.doesNotMatch(indexSource, /id="mobile-sheet"/);
assert.doesNotMatch(indexSource, /id="mobile-sheet-mode-explore-btn"/);
assert.doesNotMatch(indexSource, /id="mobile-sheet-mode-map-btn"/);
assert.doesNotMatch(indexSource, /id="mobile-sheet-actions"/);
assert.doesNotMatch(indexSource, /id="mobile-sheet-links"/);
assert.doesNotMatch(indexSource, /id="mobile-about-link"/);

console.log('mobile shell markup checks passed');
