const assert = require('node:assert/strict');
const fs = require('node:fs');

const indexSource = fs.readFileSync('index.html', 'utf8');
const appSource = fs.readFileSync('js/app.js', 'utf8');
const styleSource = fs.readFileSync('css/style.css', 'utf8');

assert.match(indexSource, /id="mobile-info-help-btn"/);
assert.match(indexSource, /id="mobile-tools-launcher-btn"/);
assert.match(indexSource, /id="mobile-dock"/);
assert.match(indexSource, /id="mobile-sheet-launcher-btn"/);
assert.match(indexSource, /id="mobile-search-launcher-btn"/);
assert.match(indexSource, /id="mobile-search-card"/);
assert.match(indexSource, /id="mobile-search-card-close-btn"/);
assert.match(indexSource, /id="mobile-search-card-title">Search</);
assert.match(indexSource, /id="mobile-search-card-search-slot"/);
assert.match(indexSource, /id="mobile-search-card-results-slot"/);
assert.match(indexSource, /id="mobile-tools-card"/);
assert.match(indexSource, /id="mobile-tools-card-close-btn"/);
assert.match(indexSource, /id="mobile-tools-panel-slot"/);
assert.match(indexSource, /id="mobile-markers-btn"/);
assert.match(indexSource, /id="mobile-filters-btn"/);
assert.match(indexSource, /id="mobile-measure-btn"/);
assert.match(indexSource, /id="mobile-sound-btn"/);
assert.match(indexSource, /id="mobile-coords-btn"/);
assert.match(indexSource, /id="mobile-share-view-btn"/);
assert.match(indexSource, /id="mobile-help-btn"/);
assert.doesNotMatch(indexSource, /id="mobile-gm-view-btn"/);
assert.doesNotMatch(indexSource, /id="mobile-toolkit-btn"/);
assert.doesNotMatch(indexSource, /id="toggle-gm-panel-btn"/);
assert.doesNotMatch(indexSource, /id="toggle-toolkit-panel-btn"/);
assert.doesNotMatch(indexSource, /id="gm-pill"/);
assert.doesNotMatch(indexSource, /id="session-toolkit"/);
assert.ok(indexSource.indexOf('id="mobile-dock"') < indexSource.indexOf('id="mobile-search-card"'));
assert.ok(indexSource.indexOf('id="mobile-search-card"') < indexSource.indexOf('id="search-control-container"'));

assert.doesNotMatch(indexSource, /id="mobile-search-panel"/);
assert.doesNotMatch(indexSource, /id="mobile-search-actions-card"/);
assert.doesNotMatch(indexSource, /id="mobile-current-map-summary-name"/);
assert.doesNotMatch(indexSource, /id="mobile-current-map-summary-blurb"/);
assert.doesNotMatch(indexSource, /id="mobile-map-list-section"/);
assert.doesNotMatch(indexSource, /id="mobile-search-panel-map-list-slot"/);

assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout #mobile-info-help-btn \{/);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout #mobile-tools-launcher-btn/);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout #mobile-search-launcher-btn \{/);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout #mobile-dock \{[\s\S]*background: transparent !important;[\s\S]*box-shadow: none !important;/m);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout #mobile-sheet-launcher-btn,\s*html\.mobile-layout-v2\.is-mobile-layout #mobile-search-launcher-btn \{[\s\S]*position: absolute !important;[\s\S]*bottom: calc\(var\(--safe-bottom\) \+ 12px\) !important;/m);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout #map-controls-container \{[\s\S]*left: calc\(var\(--safe-left\) \+ var\(--mobile-shell-gap\)\) !important;[\s\S]*flex-direction: column !important;[\s\S]*align-items: flex-start !important;/m);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout #sidebar \{[\s\S]*z-index: 1431 !important;[\s\S]*transform: translateX\(calc\(-100% - 20px\)\) !important;/m);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout \.container\.mobile-surface-atlas #sidebar \{[\s\S]*transform: translateX\(0\) !important;/m);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout #map-blurb \{/);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout #map-blurb \{[\s\S]*width: min\(300px,[\s\S]*background: var\(--mobile-card-bg\) !important;/m);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout #mobile-search-card \{/);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout #mobile-search-card \{[\s\S]*bottom: calc\(var\(--safe-bottom\) \+ 70px\) !important;[\s\S]*max-height: min\(54vh,/m);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout #mobile-tools-card \{/);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout #mobile-tools-actions \{/);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout \.container\.mobile-search-card-open #mobile-search-card,/);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout \.container\.mobile-tools-card-open #mobile-tools-card/);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout #mobile-search-card-search-slot \{/);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout #mobile-search-card-results-slot\[hidden\],/);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout \.mobile-map-blurb-card \{/);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout #mobile-search-card #search-control-container,/);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout \.leaflet-control-minimap \{[\s\S]*display: block !important;[\s\S]*margin-bottom: calc\(var\(--safe-bottom\) \+ 78px\) !important;/m);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout \.container\.mobile-search-card-open \.leaflet-control-minimap,/);
assert.match(styleSource, /html\.mobile-layout-v2\.is-mobile-layout \.container\.mobile-surface-atlas \.leaflet-control-minimap \{[\s\S]*opacity: 0 !important;[\s\S]*pointer-events: none !important;/m);

assert.match(appSource, /if \(selectedSidebarFeature && isMobileLayoutActive\) \{[\s\S]*openMobileSheet\(\{[\s\S]*mode: MOBILE_SURFACE_MODE_ATLAS,/m);
assert.match(appSource, /function selectSearchResult\(index = activeSearchResultIndex\) \{[\s\S]*closeMobileSheet\(\{ restoreFocus: false \}\);[\s\S]*if \(selectedSidebarFeature && isMobileLayoutActive\) \{[\s\S]*mode: MOBILE_SURFACE_MODE_ATLAS,/m);

console.log('mobile shell markup checks passed');
